# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ debug, release ]
        tfm: [ net462, net6.0, net8.0 ]
        rid: [ win-x64, linux-x64 ]
        exclude:
          - tfm: net462
            rid: linux-x64

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Publish
      run: dotnet publish -c ${{ matrix.configuration }} -f ${{ matrix.tfm }} -r ${{ matrix.rid }} ./src/SspiSample/SspiSample.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ matrix.tfm }} ${{ matrix.rid }} ${{ matrix.configuration }}
        path: artifacts/publish/SspiSample/**/*

