# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore dependencies
      run: dotnet build -c RELEASE
    - name: Publish net462
      run: dotnet publish -c RELEASE -f net462 -r win-x64 --no-restore --no-build ./src/SspiSample/SspiSample.csproj
    - name: Publish net6.0
      run: dotnet publish -c RELEASE -f net6.0 --sc --no-restore --no-build ./src/SspiSample/SspiSample.csproj
    - name: Publish net8.0
      run: dotnet publish -c RELEASE -f net8.0 --sc --no-restore --no-build ./src/SspiSample/SspiSample.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: artifacts/publish/SspiSample/**/*
